# Ngày 27: Matrix with Numpy
https://drive.google.com/file/d/12zSGrYa3iw6NcUBmy0c55SCDbD5jewee/view

In [1]:
pip install numpy

Bài Tập 1: Tạo Ma Trận
Viết mã Python để tạo một ma trận 3 × 3 với các phần tử ngẫu nhiên.

In [4]:
import numpy as np
matrix = np.random.rand(3, 3)
print("Ma trận 3x3 với các phần tử ngẫu nhiên:\n", matrix)

Ma trận 3x3 với các phần tử ngẫu nhiên:
 [[0.6812416  0.12435633 0.65704992]
 [0.53257843 0.29431179 0.46203688]
 [0.43767952 0.73069744 0.07602727]]


Bài Tập 2: Phép Cộng Ma Trận
Viết mã Python để cộng hai ma trận 3 × 3.

In [5]:
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)
matrix_sum = matrix1 + matrix2
print("Tổng của hai ma trận:\n", matrix_sum)

Tổng của hai ma trận:
 [[0.59011994 1.30400246 0.96200573]
 [1.64735826 0.96131778 1.29088542]
 [1.07258072 1.58680096 1.64086276]]


Bài Tập 3: Phép Nhân Ma Trận
Viết mã Python để nhân hai ma trận 3 × 3 (Sử dụng np.dot hoặc ký hiệu @ để nhân hai ma trận)

In [6]:
matrix_product = np.dot(matrix1, matrix2)
print("Tích của hai ma trận:\n", matrix_product)

Tích của hai ma trận:
 [[0.57380512 1.02351375 0.88424748]
 [0.59093463 1.10844802 0.95662698]
 [0.99858872 2.06199131 1.729249  ]]


Bài Tập 4: Ma Trận Chuyển Vị
Viết mã Python để tìm ma trận chuyển vị của một ma trận 3 × 3 (Dùng .T để lấy ma trận chuyển vị)

In [7]:
matrix_transpose = matrix.T
print("Ma trận chuyển vị:\n", matrix_transpose)

Ma trận chuyển vị:
 [[0.6812416  0.53257843 0.43767952]
 [0.12435633 0.29431179 0.73069744]
 [0.65704992 0.46203688 0.07602727]]


Bài Tập 5: Ma Trận Nghịch Đảo
Viết mã Python để tìm ma trận nghịch đảo của một ma trận 3 × 3 (nếu có) (Sử dụng np.linalg.inv, và nhớ kiểm tra nếu ma trận không khả nghịch):

In [8]:
try:
    matrix_inverse = np.linalg.inv(matrix)
    print("Ma trận nghịch đảo:\n", matrix_inverse)
except np.linalg.LinAlgError:
    print("Ma trận không khả nghịch")

Ma trận nghịch đảo:
 [[ 13.36781576 -19.95843284   5.76384878]
 [ -6.8584885    9.99869131  -1.4915014 ]
 [-11.03997644  18.8008759   -5.69377725]]


Bài Tập 6: Tính Định Thức Ma Trận
Viết mã Python để tính định thức của một ma trận 3 × 3 (Dùng np.linalg.det để tính định thức):

In [9]:
det = np.linalg.det(matrix)
print("Định thức của ma trận:\n", det)

Định thức của ma trận:
 -0.023581521997367693
